/*
 * Clay configuration page (shown in the Pebble phone app under the gear icon).
 * Built per language from src/pkjs/i18n.js (generated by tools/i18n.py).
 * The messageKeys used here must exist in package.json -> pebble.messageKeys.
 */
var i18n = require('./i18n');

module.exports = function buildConfig(lang) {
  var t = i18n.phone[lang] || i18n.phone.en;
  var langOptions = [{ label: t.language_auto, value: '0' }];
  i18n.langs.forEach(function (code, i) {
    langOptions.push({ label: i18n.native[code], value: String(i + 1) });
  });
  return [
    { type: 'heading', defaultValue: 'HELO Remote' },
    { type: 'text', defaultValue: t.intro },
    {
      type: 'section',
      items: [
        { type: 'heading', defaultValue: t.section_helo },
        {
          type: 'input', messageKey: 'HELO_HOST', label: t.host_label, defaultValue: '',
          attributes: { placeholder: t.host_placeholder, autocapitalize: 'off', autocorrect: 'off' }
        },
        {
          type: 'input', messageKey: 'HELO_PORT', label: t.port_label, defaultValue: '80',
          attributes: { type: 'number', min: 1, max: 65535 }
        },
        {
          type: 'input', messageKey: 'HELO_PASSWORD', label: t.password_label, defaultValue: '',
          attributes: { type: 'password', placeholder: t.password_placeholder }
        }
      ]
    },
    {
      type: 'section',
      items: [
        { type: 'heading', defaultValue: t.section_monitoring },
        { type: 'slider', messageKey: 'POLL_INTERVAL', label: t.poll_label, defaultValue: 3, min: 1, max: 15, step: 1 },
        { type: 'toggle', messageKey: 'VIBRATE', label: t.vibrate_label, defaultValue: true }
      ]
    },
    {
      type: 'section',
      items: [
        { type: 'heading', defaultValue: t.section_display },
        { type: 'select', messageKey: 'LANGUAGE', label: t.language_label, defaultValue: '0', options: langOptions }
      ]
    },
    {
      type: 'section',
      items: [
        { type: 'heading', defaultValue: t.section_timeline },
        { type: 'toggle', messageKey: 'TIMELINE', label: t.timeline_label, defaultValue: true, description: t.timeline_note },
        {
          type: 'input', messageKey: 'TIMELINE_HOST', label: t.timeline_host_label,
          defaultValue: 'https://timeline-api.rebble.io',
          attributes: { placeholder: 'https://timeline-api.rebble.io', autocapitalize: 'off', autocorrect: 'off' }
        }
      ]
    },
    { type: 'text', defaultValue: t.keys_text },
    { type: 'submit', defaultValue: t.save },
    {
      type: 'section',
      items: [
        { type: 'heading', defaultValue: t.support },
        { type: 'text', defaultValue: t.support_text },
        { type: 'button', id: 'donate', primary: true, defaultValue: t.donate }
      ]
    }
  ];
};
